apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  namespace: lxp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: keycloak-db-secret
          ports:
            - containerPort: 5432
