apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: lxp
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30090
    - port: 9001
      nodePort: 30091
  selector:
    app: minio
