version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "8084:8080"       # Jenkins web UI
      - "50000:50000"     # Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # allow Jenkins to run Docker
      - /usr/bin/docker:/usr/bin/docker             # docker CLI inside Jenkins
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
    driver: bridge
